export const MODES = [
  {
    id: "ar",
    icon: "📸",
    title: "AR MODE",
    subtitle: "Camera + Hand Gestures",
    description: "Use your real hand in front of the camera. AI detects your gesture automatically.",
    borderHue: 217,
    accentHsl: "hsl(217 91% 60%)",
    glowHsl: "hsl(217 91% 60% / 0.25)",
    gradientFrom: "hsl(217 91% 55%)",
    gradientTo: "hsl(280 85% 60%)",
  },
  {
    id: "tap",
    icon: "⚡",
    title: "TAP MODE",
    subtitle: "Arcade Speed Play",
    description: "Quick gameplay with on-screen buttons. No camera needed. Pure reflexes.",
    borderHue: 280,
    accentHsl: "hsl(280 85% 65%)",
    glowHsl: "hsl(280 85% 65% / 0.25)",
    gradientFrom: "hsl(280 85% 55%)",
    gradientTo: "hsl(320 70% 55%)",
  },
  {
    id: "daily",
    icon: "📅",
    title: "DAILY CHALLENGE",
    subtitle: "New Target Every Day",
    description: "Beat today's target score. One shot per day — share your result!",
    borderHue: 43,
    accentHsl: "hsl(43 93% 50%)",
    glowHsl: "hsl(43 93% 50% / 0.25)",
    gradientFrom: "hsl(43 90% 50%)",
    gradientTo: "hsl(35 80% 40%)",
  },
  {
    id: "multiplayer",
    icon: "⚔️",
    title: "MULTIPLAYER",
    subtitle: "Real-Time PvP",
    description: "Challenge friends in real-time hand cricket matches online.",
    borderHue: 0,
    accentHsl: "hsl(0 84% 60%)",
    glowHsl: "hsl(0 84% 60% / 0.2)",
    gradientFrom: "hsl(350 75% 55%)",
    gradientTo: "hsl(0 84% 50%)",
  },
  {
    id: "tournament",
    icon: "🏆",
    title: "TOURNAMENT",
    subtitle: "5-Round Bracket",
    description: "Battle through 5 AI opponents of increasing difficulty to become champion.",
    borderHue: 43,
    accentHsl: "hsl(43 100% 55%)",
    glowHsl: "hsl(43 100% 55% / 0.25)",
    gradientFrom: "hsl(43 100% 50%)",
    gradientTo: "hsl(217 80% 55%)",
  },
  {
    id: "ipl",
    icon: "🏟️",
    title: "IPL SEASON",
    subtitle: "Full Tournament",
    description: "Pick a franchise and battle through group stage, playoffs, and the grand final.",
    borderHue: 25,
    accentHsl: "hsl(25 90% 55%)",
    glowHsl: "hsl(25 90% 55% / 0.25)",
    gradientFrom: "hsl(25 90% 50%)",
    gradientTo: "hsl(45 100% 50%)",
  },
  {
    id: "royale",
    icon: "💀",
    title: "CRICKET ROYALE",
    subtitle: "Battle Royale",
    description: "Survive 5 rounds of shrinking overs. Beat the target or get eliminated!",
    borderHue: 280,
    accentHsl: "hsl(280 70% 55%)",
    glowHsl: "hsl(280 70% 55% / 0.25)",
    gradientFrom: "hsl(280 70% 50%)",
    gradientTo: "hsl(340 80% 50%)",
  },
  {
    id: "practice",
    icon: "🎯",
    title: "PRACTICE",
    subtitle: "Learn & Improve",
    description: "Practice your gestures without scoring. See what the AI detects in real time.",
    borderHue: 142,
    accentHsl: "hsl(142 71% 45%)",
    glowHsl: "hsl(142 71% 45% / 0.25)",
    gradientFrom: "hsl(142 71% 45%)",
    gradientTo: "hsl(180 60% 40%)",
  },
];

export type GameMode = typeof MODES[number];
